[build]
target-dir = "./.cargo/shared/target"

[alias]

# 构建相关
build_dev = ["build", "--workspace", "--profile", "dev"]
build_release = ["build", "--workspace", "--profile", "release"]

# 打包相关
dev = [ "run", "--manifest-path", "./Cargo.toml", "--profile", "dev", "--bin", "export_porject", "dev" ]
release = [ "run", "--manifest-path", "./Cargo.toml", "--profile", "release", "--bin", "export_porject" ]

[env]
# ------ 项目设置 ------

# 项目版本
PROJECT_VERSION = { value = "0.1.3" }

# ----- 服务器设置 -----

# 默认端口
DEFAULT_SERVER_PORT = { value = "5011" }

# ------ 路径设置 ------

# 路径
PATH_WORKSPACE_ROOT = { value = ".jam/" }
PATH_PARAMETERS = { value = ".jam/Params/" }
PATH_DATABASE_CONFIG_ARCHIVE = { value = ".jam/_Archived/" }
PATH_CACHE = { value = ".jam/_Cache/" }
PATH_DATABASE = { value = "Storage/" }

# 文件
FILE_DATABASE = { value = ".jam/DBRemote.yaml" }
FILE_LOCAL_FILE_MAP = { value = ".jam/DBLocal.yaml" }
FILE_LOCAL_FOLDER_MAP = { value = ".jam/_StructCache.yaml" }
FILE_WORKSPACE_SERVER_DATA = { value = ".jam/Settings.yaml" }

# ----- 工作区设置 -----

# 工作区回收站
WORKSPACE_RECYCLEBIN = { value = "Removed/" }