[build]
target-dir = "./.shared/target"

[alias]

# Build related
build_dev = ["build", "--workspace", "--profile", "dev"]
build_release = ["build", "--workspace", "--profile", "release"]

# Packaging related
dev = [ "run", "--manifest-path", "./Cargo.toml", "--profile", "dev", "--bin", "export_project", "dev" ]
release = [ "run", "--manifest-path", "./Cargo.toml", "--profile", "release", "--bin", "export_project" ]

[env]
# ------ Project Settings ------

# Project version
PROJECT_VERSION = { value = "0.1.3" }

# ----- Server Settings -----

# Default port
DEFAULT_SERVER_PORT = { value = "5011" }

# ------ Path Settings ------

# In the .jam directory,     names should use "lower_snake_case",
# while other directories or files should use " UpperCamelCase ".

# Paths
PATH_WORKSPACE_ROOT = { value = ".jam/" }
PATH_PARAMETERS = { value = ".jam/params/" }
PATH_DATABASE_CONFIG_ARCHIVE = { value = ".jam/.archived/" }
PATH_CACHE = { value = ".jam/.cached/" }
PATH_DATABASE = { value = "Storage/" }

# Files
FILE_DATABASE = { value = ".jam/db_remote.ron" }
FILE_LOCAL_FILE_MAP = { value = ".jam/db_local.ron" }
FILE_LOCAL_FOLDER_MAP = { value = ".jam/.struct_cache.ron" }
FILE_WORKSPACE_SERVER_DATA = { value = ".jam/workspace.ron" }

# ----- Workspace Settings -----

# Workspace recycle bin
WORKSPACE_RECYCLEBIN = { value = "Removed/" }