# Export from "project_root" to "target_folder"
[release.root]

# GUI packaging
 gui_executable_files = { raw = "./.shared/target/dotnet/gui/bin/JamReadyGui/Release/", target = "./bin/", files = [
     "publish/"
 ] }

# Installation scripts (Windows)
installation_scripts_win = { raw = "./.cargo/scripts/installation/", target = "./scripts/win/", files = [

    "_INSTALL_WIN.ps1",
    "_UNINSTALL_WIN.ps1",

    "completion_script_jam.ps1",
    "install_completions.ps1",
    "install_cli.ps1"
] }

# Installation scripts (Linux)
installation_scripts_linux = { raw = "./.cargo/scripts/installation/", target = "./scripts/linux/", files = [

    # Linux
    "completion_script_jam.sh",
    "install_completions.sh",
    "uninstall_completions.sh",
] }

# Export from "build_folder" to "target_folder"
[release.deps]

# Executable files
executable_files = { raw = "./", target = "./bin/", files = [

    # Windows
    "jam.exe",
    "jamlinker.exe",

    # Linux / Unix
    "jam",
    "jamlinker"
] }

# Deploy from "project_root" to "target_folder"
[release.deploy_root]

# Deploy from "build_folder" to "target_folder"
[release.deploy_deps]

# Executable files
# deploy_executable_files = { raw = "./", target = "./app/JamReadyApp/JamReadyAppUtils/bin/Debug/net9.0/Binaries/", files = [
#
#     # Windows
#     "jam.exe",
#
#     # Linux / Unix
#     "jam"
# ] }