# 从 “项目文件夹” 导出到 “打包文件夹”
[release.root]

# Windows 下 Powershell 的补全脚本安装
win_ps_completions = { raw = "./.cargo/completions/", target = "./bin", files = [
    "install_completions.ps1"
] }

# 从 “编译文件夹” 导出到 “打包文件夹”
[release.deps]

# 可执行文件 (Windows)
win_exes = { raw = "./", target = "./bin", files = [
    "jam.exe"
] }

# 从 “项目文件夹” 部署到 “项目文件夹” (复制)
[release.deploy_root]

# 从 “编译文件夹” 部署到 “项目文件夹” (复制)
[release.deploy_deps]

# 可执行文件部署到 jam-ready-gui (Windows)
win_exes = { raw = "./", target = "./jam-ready-gui/JamReadyExplorer/bin/Work/bin/", files = [
    "jam.exe"
] }